### ISSUE TITLE
wasmvm module not exist 

### ISSUE THREAD

**Issue by zemyblue** [line/wasmd#13]
When I run `wasmd start`, `wasmvm module not exist` error is occurred. 

```shell
$ ./build/wasmd start
Error: wasmvm module not exist
Usage:
  wasmd start [flags]
```

commit hash: 577e45074b4be98523b4c12ac8eb4d316c5e2e5e (main branch)

**Comment by loin3** [comment]
I am getting same error.
```
go: downloading github.com/line/wasmvm v1.1.1-0.11.1
go: downloading github.com/gin-gonic/gin v1.7.0
verifying github.com/line/wasmvm@v1.1.1-0.11.1: checksum mismatch
	downloaded: h1:sCnlvj3oLOjaUcn+awofP2EXMjngV4UOpwuqnNYDW6c=
	go.sum:     h1:W3fuNZyQYm+fyXV4n6Ds8pzmHLyYcgv5gXgQf42ofi8=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

**Comment by zemyblue** [comment]
I think we replace the github import name from `github.com/CosmWasm/wasmvm` to `github.com/line/wasmvm`.
https://github.com/line/wasmd/blob/577e45074b4be98523b4c12ac8eb4d316c5e2e5e/x/wasm/module.go#L259-L268

**Comment by zemyblue** [comment]
I think we replace the github import name from `github.com/CosmWasm/wasmvm` to `github.com/line/wasmvm`.
https://github.com/line/wasmd/blob/577e45074b4be98523b4c12ac8eb4d316c5e2e5e/x/wasm/module.go#L259-L268

**Comment by zemyblue** [comment]
> 

@loin3 , When did you receive this error? What is the command?

**Comment by loin3** [comment]
I got this error when `make install` in commit `577e4507`. but after deleting go.sum and download again, it works.

**Comment by zemyblue** [comment]
When I modify the dep path from `github.com/CosmWasm/wasmvm` to `github.com/line/wasmvm`, the other error is occurred. 
```shell
Error: libwasmversion mismatch. got: 1.1.1-0.11.0; expected: v1.1.1-0.11.1
```

I think the library in the [line/wasmvm](https://github.com/line/wasmvm)'s `v1.1.1-0.11.1` tag looks wrong version.


We need to update right library in wasmvm repo.

**Comment by zemyblue** [comment]
I think we need to add a test that the setting of `line/wasmvm` and the library version are correct.

**Comment by tkxkd0159** [comment]
`wasmvm v1.1.1-0.11.1'`s checksum is not correct now. We need to fix it
